isClass(agent).
isClass(artefact).
isClass(change_goal).
isClass(compatibility).
isClass(condition).
isClass(condition_relation_artefact_artefact).
isClass(condition_relation_role_tool).
isClass(condition_sanction).
isClass(condition_without_relation_entity).
isClass(deontic_relation).
isClass(entity).
isClass(entity_fatality).
isClass(goal).
isClass(goal_mission).
isClass(group).
isClass(group_role).
isClass(group_safety).
isClass(group_safety_risk).
isClass(heritage).
isClass(link).
isClass(long_consequence).
isClass(mission).
isClass(object).
isClass(plan).
isClass(plan_goal).
isClass(relation_artefact_artefact).
isClass(relation_role_tool).
isClass(risk).
isClass(role).
isClass(role_allocation).
isClass(sanction).
isClass(schema).
isClass(short_consequence).
isClass(tool).
isClass(trigger_sanction).


extend(agent,entity).
extend(artefact,entity).
extend(tool,artefact).
extend(obect,artefact).


isInstanceOf(agente01,entity).
isInstanceOf(agente02,entity).
isInstanceOf(agente03,entity).
isInstanceOf(agente04,entity).
isInstanceOf(agente05,entity).
isInstanceOf(agente06,entity).
isInstanceOf(agente07,entity).
isInstanceOf(agente08,entity).
isInstanceOf(agente09,entity).
isInstanceOf(cone,entity).
isInstanceOf(fita,entity).
isInstanceOf(carretilha,entity).
isInstanceOf(corda,entity).
isInstanceOf(bastao_universal,entity).
isInstanceOf(testador_de_corrente_de_fulga,entity).
isInstanceOf(sela,entity).
isInstanceOf(colar,entity).
isInstanceOf(bastao_garra,entity).
isInstanceOf(estopo,entity).
isInstanceOf(chave_catraca,entity).
isInstanceOf(condutor,entity).
isInstanceOf(torre,entity).
isInstanceOf(isolador_de_pedestal_velho,entity).
isInstanceOf(isolador_de_pedestal_novo,entity).
isInstanceOf(conector,entity).
isInstanceOf(luva,entity).
isInstanceOf(óculos,entity).
isInstanceOf(chão,entity).
isInstanceOf(torres,entity).
isInstanceOf(cavalete,entity).
isInstanceOf(alcool_isopropilico,entity).
isInstanceOf(pano_seco,entity).
isInstanceOf(parafuso,entity).

isInstanceOf(cone,artefact).
isInstanceOf(fita,artefact).
isInstanceOf(carretilha,artefact).
isInstanceOf(corda,artefact).
isInstanceOf(bastao_universal,artefact).
isInstanceOf(testador_de_corrente_de_fulga,artefact).
isInstanceOf(sela,artefact).
isInstanceOf(colar,artefact).
isInstanceOf(bastao_garra,artefact).
isInstanceOf(estopo,artefact).
isInstanceOf(chave_catraca,artefact).
isInstanceOf(condutor,artefact).
isInstanceOf(torre,artefact).
isInstanceOf(isolador_de_pedestal_velho,artefact).
isInstanceOf(isolador_de_pedestal_novo,artefact).
isInstanceOf(conector,artefact).
isInstanceOf(luva,artefact).
isInstanceOf(óculos,artefact).
isInstanceOf(chão,artefact).
isInstanceOf(torres,entity).
isInstanceOf(cavalete,artefact).
isInstanceOf(alcool_isopropilico,artefact).
isInstanceOf(pano_seco,artefact).
isInstanceOf(parafuso,artefact).

isInstanceOf(cone,tool).
isInstanceOf(fita,tool).
isInstanceOf(carretilha,tool).
isInstanceOf(corda,tool).
isInstanceOf(bastao_universal,tool).
isInstanceOf(testador_de_corrente_de_fulga,tool).
isInstanceOf(sela,tool).
isInstanceOf(colar,tool).
isInstanceOf(bastao_garra,tool).
isInstanceOf(estopo,tool).
isInstanceOf(chave_catraca,tool).
isInstanceOf(condutor,tool).
isInstanceOf(luva,tool).
isInstanceOf(óculos,tool).

isInstanceOf(condutor,object).
isInstanceOf(torre,object).
isInstanceOf(isolador_de_pedestal_velho,object).
isInstanceOf(isolador_de_pedestal_novo,object).
isInstanceOf(conector,object).
isInstanceOf(parafuso,object).

isInstanceOf(analize_preliminar_risco,condition).
isInstanceOf(procedimentos-iniciais,condition).
isInstanceOf(sinalizacao,condition).
isInstanceOf(cavalete,condition).
isInstanceOf(limpar-ferramenta,condition).
isInstanceOf(medicao-corrente-fulga-inicio-manutencao,condition).
isInstanceOf(medicao-corrente-fulga-durante-manutencao,condition).
isInstanceOf(medicao-corrente-fulga-final-operacao,condition).
isInstanceOf(posicionamento-cavalete,condition).
isInstanceOf(procedimentos-corda-manutencao-carretilha,condition).
isInstanceOf(verificar-corda-limpa,condition).
isInstanceOf(teste-impedancia-corda,condition).
isInstanceOf(rasga-corda-pedacos,condition).
isInstanceOf(interpolar-corda-bastao-universal,condition).
isInstanceOf(fixar-carretilha-corda-bastao-universal,condition).
isInstanceOf(instalar-sela-corda-lado-1,condition).
isInstanceOf(fixar-bastao-garra-colar-sela,condition).
isInstanceOf(fixar-bastao-garra-lado-1-condutor,condition).
isInstanceOf(instalar-sela-colar-coluna-lado-2,condition).
isInstanceOf(fixar-bastao-garra-invertido-lado-2,condition).
isInstanceOf(fixar-carretilha-corda-fibra-sintetica-ponta-bastao,condition).
isInstanceOf(girar-sela-erguer-bastao,condition).
isInstanceOf(enforcar-estopo-alto-isolador,condition).
isInstanceOf(conectar-corda-estopo,condition).
isInstanceOf(operacao-isolador-pedestal,condition).
isInstanceOf(bastao-universal-chave-catraca-saltar-parafusos,condition).
isInstanceOf(retirar-parafuso-cima,condition).
isInstanceOf(finalizar-troca-isolador-pedestal,condition).
isInstanceOf(tencionar-corda-estopo,condition).
isInstanceOf(tirar-parafusos-baixo-isolador-chave-catraca,condition).
isInstanceOf(passar-corda-base-isolador-chave-catraca,condition).
isInstanceOf(corda-erguer-isolador,condition).
isInstanceOf(retirar-isolador-antigo,condition).
isInstanceOf(estopo-isolador,condition).
isInstanceOf(suspender-isolador,condition).
isInstanceOf(engate-corda-guia,condition).
isInstanceOf(icar-isolador,condition).
isInstanceOf(parafusar-isolador-coluna-chave-catraca,condition).
isInstanceOf(fechar-conector-bastao-universal,condition).
isInstanceOf(desconectar-batao-garra-conector,condition).
isInstanceOf(retirar-bastao-garra,condition).
isInstanceOf(retirar-sela-colar-bastao-garra-lado-1,condition).
isInstanceOf(retirar-estopo-isolador,condition).
isInstanceOf(retirar-sela-colar-bastao-garra-lado-2,condition).
isInstanceOf(recolher-equipamento,condition).
isInstanceOf(metodo-a-distancia,condition).
isInstanceOf(supervisao,condition).
isInstanceOf(observacao,condition).
isInstanceOf(objetivo-final,condition).
isInstanceOf(etapas-metodologicas,condition).
isInstanceOf(metodo-finalizado,condition).

isInstanceOf(supervisores,group).
isInstanceOf(observadores,group).
isInstanceOf(executores,group).


isInstanceOf(plan1,plan).
isInstanceOf(plan2,plan).
isInstanceOf(plan3,plan).
isInstanceOf(plan4,plan).
isInstanceOf(plan5,plan).
isInstanceOf(plan6,plan).
isInstanceOf(plan7,plan).
isInstanceOf(plan8,plan).

hasType(plan1,sequence).
hasType(plan2,sequence).
hasType(plan3,sequence).
hasType(plan4,sequence).
hasType(plan5,sequence).
hasType(plan6,parallel).
hasType(plan7,parallel).
hasType(plan8,parallel).


hasSuperGoal(plan1,goal50).
hasSuperGoal(plan2,goal51).
hasSuperGoal(plan3,goal10).
hasSuperGoal(plan4,goal25).
hasSuperGoal(plan5,goal28).
hasSuperGoal(plan6,goal49).
hasSuperGoal(plan7,goal2).
hasSuperGoal(plan8,goal49).


isInstanceOf(missao00,mission).
isInstanceOf(missao01-01,mission).
isInstanceOf(missao01-02,mission).
isInstanceOf(missao01-03,mission).
isInstanceOf(missao01-04,mission).
isInstanceOf(missao01-05,mission).
isInstanceOf(missao01-06,mission).
isInstanceOf(missao02,mission).
isInstanceOf(missao03,mission).
isInstanceOf(missao04,mission).
isInstanceOf(missao05,mission).
isInstanceOf(missao06,mission).
isInstanceOf(missao07,mission).
isInstanceOf(missao08,mission).
isInstanceOf(missao09,mission).
isInstanceOf(missao10,mission).
isInstanceOf(missao11,mission).
isInstanceOf(missao12,mission).

isInstanceOf(schema01,schema).

hasSchema(missao0,schema01).
hasSchema(missao01-01,schema01).
hasSchema(missao01-02,schema01).
hasSchema(missao01-03,schema01).
hasSchema(missao01-04,schema01).
hasSchema(missao01-05,schema01).
hasSchema(missao01-06,schema01).
hasSchema(missao02,schema01).
hasSchema(missao03,schema01).
hasSchema(missao04,schema01).
hasSchema(missao05,schema01).
hasSchema(missao06,schema01).
hasSchema(missao07,schema01).
hasSchema(missao08,schema01).
hasSchema(missao09,schema01).
hasSchema(missao10,schema01).
hasSchema(missao11,schema01).
hasSchema(missao12,schema01).

isInstanceOf(supervisor,role).
isInstanceOf(observador,role).
isInstanceOf(executor01,role).
isInstanceOf(executor02,role).
isInstanceOf(executor03,role).
isInstanceOf(executor04,role).
isInstanceOf(executor05,role).
isInstanceOf(executor06,role).
isInstanceOf(executor07,role).

isInstanceOf(goal1,goal).
isInstanceOf(goal2,goal).
isInstanceOf(goal3,goal).
isInstanceOf(goal4,goal).
isInstanceOf(goal5,goal).
isInstanceOf(goal6,goal).
isInstanceOf(goal7,goal).
isInstanceOf(goal8,goal).
isInstanceOf(goal9,goal).
isInstanceOf(goal10,goal).
isInstanceOf(goal11,goal).
isInstanceOf(goal12,goal).
isInstanceOf(goal13,goal).
isInstanceOf(goal14,goal).
isInstanceOf(goal15,goal).
isInstanceOf(goal16,goal).
isInstanceOf(goal17,goal).
isInstanceOf(goal18,goal).
isInstanceOf(goal19,goal).
isInstanceOf(goal20,goal).
isInstanceOf(goal21,goal).
isInstanceOf(goal22,goal).
isInstanceOf(goal23,goal).
isInstanceOf(goal24,goal).
isInstanceOf(goal25,goal).
isInstanceOf(goal26,goal).
isInstanceOf(goal27,goal).
isInstanceOf(goal28,goal).
isInstanceOf(goal29,goal).
isInstanceOf(goal30,goal).
isInstanceOf(goal31,goal).
isInstanceOf(goal32,goal).
isInstanceOf(goal33,goal).
isInstanceOf(goal34,goal).
isInstanceOf(goal35,goal).
isInstanceOf(goal36,goal).
isInstanceOf(goal37,goal).
isInstanceOf(goal38,goal).
isInstanceOf(goal39,goal).
isInstanceOf(goal40,goal).
isInstanceOf(goal41,goal).
isInstanceOf(goal42,goal).
isInstanceOf(goal43,goal).
isInstanceOf(goal44,goal).
isInstanceOf(goal45,goal).
isInstanceOf(goal46,goal).
isInstanceOf(goal47,goal).
isInstanceOf(goal48,goal).
isInstanceOf(goal49,goal).
isInstanceOf(goal50,goal).
isInstanceOf(goal51,goal).


hasProbabilitiy(goal1,95).
hasProbabilitiy(goal2,95).
hasProbabilitiy(goal3,95).
hasProbabilitiy(goal4,95).
hasProbabilitiy(goal5,95).
hasProbabilitiy(goal6,95).
hasProbabilitiy(goal7,95).
hasProbabilitiy(goal8,95).
hasProbabilitiy(goal9,95).
hasProbabilitiy(goal10,95).
hasProbabilitiy(goal11,95).
hasProbabilitiy(goal12,95).
hasProbabilitiy(goal13,95).
hasProbabilitiy(goal14,95).
hasProbabilitiy(goal15,95).
hasProbabilitiy(goal16,95).
hasProbabilitiy(goal17,95).
hasProbabilitiy(goal18,95).
hasProbabilitiy(goal19,95).
hasProbabilitiy(goal20,95).
hasProbabilitiy(goal21,95).
hasProbabilitiy(goal22,95).
hasProbabilitiy(goal23,95).
hasProbabilitiy(goal24,95).
hasProbabilitiy(goal25,95).
hasProbabilitiy(goal26,95).
hasProbabilitiy(goal27,95).
hasProbabilitiy(goal28,95).
hasProbabilitiy(goal29,95).
hasProbabilitiy(goal30,95).
hasProbabilitiy(goal31,95).
hasProbabilitiy(goal32,95).
hasProbabilitiy(goal33,95).
hasProbabilitiy(goal34,95).
hasProbabilitiy(goal35,95).
hasProbabilitiy(goal36,95).
hasProbabilitiy(goal37,95).
hasProbabilitiy(goal38,95).
hasProbabilitiy(goal39,95).
hasProbabilitiy(goal40,95).
hasProbabilitiy(goal41,95).
hasProbabilitiy(goal42,95).
hasProbabilitiy(goal43,95).
hasProbabilitiy(goal44,95).
hasProbabilitiy(goal45,95).
hasProbabilitiy(goal46,95).
hasProbabilitiy(goal47,95).
hasProbabilitiy(goal48,95).
hasProbabilitiy(goal49,95).
hasProbabilitiy(goal50,95).
hasProbabilitiy(goal51,95).


isInstanceOf(condition1,condition).
isInstanceOf(condition2,condition).
isInstanceOf(condition3,condition).
isInstanceOf(condition4,condition).
isInstanceOf(condition5,condition).
isInstanceOf(condition6,condition).
isInstanceOf(condition7,condition).
isInstanceOf(condition8,condition).
isInstanceOf(condition9,condition).
isInstanceOf(condition10,condition).
isInstanceOf(condition11,condition).
isInstanceOf(condition12,condition).
isInstanceOf(condition13,condition).
isInstanceOf(condition14,condition).
isInstanceOf(condition15,condition).
isInstanceOf(condition16,condition).
isInstanceOf(condition17,condition).
isInstanceOf(condition18,condition).
isInstanceOf(condition19,condition).
isInstanceOf(condition20,condition).
isInstanceOf(condition21,condition).
isInstanceOf(condition22,condition).
isInstanceOf(condition23,condition).
isInstanceOf(condition24,condition).
isInstanceOf(condition25,condition).
isInstanceOf(condition26,condition).
isInstanceOf(condition27,condition).
isInstanceOf(condition28,condition).
isInstanceOf(condition29,condition).
isInstanceOf(condition30,condition).
isInstanceOf(condition31,condition).
isInstanceOf(condition32,condition).
isInstanceOf(condition33,condition).
isInstanceOf(condition34,condition).
isInstanceOf(condition35,condition).
isInstanceOf(condition36,condition).
isInstanceOf(condition37,condition).
isInstanceOf(condition38,condition).
isInstanceOf(condition39,condition).
isInstanceOf(condition40,condition).
isInstanceOf(condition41,condition).
isInstanceOf(condition42,condition).
isInstanceOf(condition43,condition).
isInstanceOf(condition44,condition).
isInstanceOf(condition45,condition).
isInstanceOf(condition46,condition).
isInstanceOf(condition47,condition).
isInstanceOf(condition48,condition).
isInstanceOf(condition49,condition).
isInstanceOf(condition50,condition).
isInstanceOf(condition51,condition).


hasName(condition1,analize_preliminar_risco).
hasName(condition2,procedimentos-iniciais).
hasName(condition3,sinalizacao).
hasName(condition4,cavalete).
hasName(condition5,limpar-ferramenta).
hasName(condition6,medicao-corrente-fulga-inicio-manutencao).
hasName(condition7,medicao-corrente-fulga-durante-manutencao).
hasName(condition8,medicao-corrente-fulga-final-operacao).
hasName(condition9,posicionamento-cavalete).
hasName(condition10,procedimentos-corda-manutencao-carretilha).
hasName(condition11,verificar-corda-limpa).
hasName(condition12,teste-impedancia-corda).
hasName(condition13,rasga-corda-pedacos).
hasName(condition14,interpolar-corda-bastao-universal).
hasName(condition15,fixar-carretilha-corda-bastao-universal).
hasName(condition16,instalar-sela-corda-lado-1).
hasName(condition17,fixar-bastao-garra-colar-sela).
hasName(condition18,fixar-bastao-garra-lado-1-condutor).
hasName(condition19,instalar-sela-colar-coluna-lado-2).
hasName(condition20,fixar-bastao-garra-invertido-lado-2).
hasName(condition21,fixar-carretilha-corda-fibra-sintetica-ponta-bastao).
hasName(condition22,girar-sela-erguer-bastao).
hasName(condition23,enforcar-estopo-alto-isolador).
hasName(condition24,conectar-corda-estopo).
hasName(condition25,operacao-isolador-pedestal).
hasName(condition26,bastao-universal-chave-catraca-saltar-parafusos).
hasName(condition27,retirar-parafuso-cima).
hasName(condition28,finalizar-troca-isolador-pedestal).
hasName(condition29,tencionar-corda-estopo).
hasName(condition30,tirar-parafusos-baixo-isolador-chave-catraca).
hasName(condition31,passar-corda-base-isolador-chave-catraca).
hasName(condition32,corda-erguer-isolador).
hasName(condition33,retirar-isolador-antigo).
hasName(condition34,estopo-isolador).
hasName(condition35,suspender-isolador).
hasName(condition36,engate-corda-guia).
hasName(condition37,icar-isolador).
hasName(condition38,parafusar-isolador-coluna-chave-catraca).
hasName(condition39,fechar-conector-bastao-universal).
hasName(condition40,desconectar-batao-garra-conector).
hasName(condition41,retirar-bastao-garra).
hasName(condition42,retirar-sela-colar-bastao-garra-lado-1).
hasName(condition43,retirar-estopo-isolador).
hasName(condition44,retirar-sela-colar-bastao-garra-lado-2).
hasName(condition45,recolher-equipamento).
hasName(condition46,metodo-a-distancia).
hasName(condition47,supervisao).
hasName(condition48,observacao).
hasName(condition49,objetivo-final).
hasName(condition50,etapas-metodologicas).
hasName(condition51,metodo-finalizado).


hasCondition(goal1,condition1,)
hasCondition(goal2,condition2,)
hasCondition(goal3,condition3,)
hasCondition(goal4,condition4,)
hasCondition(goal5,condition5,)
hasCondition(goal6,condition6,)
hasCondition(goal7,condition7,)
hasCondition(goal8,condition8,)
hasCondition(goal9,condition9,)
hasCondition(goal10,condition10).
hasCondition(goal11,condition11).
hasCondition(goal12,condition12).
hasCondition(goal13,condition13).
hasCondition(goal14,condition14).
hasCondition(goal15,condition15).
hasCondition(goal16,condition16).
hasCondition(goal17,condition17).
hasCondition(goal18,condition18).
hasCondition(goal19,condition19).
hasCondition(goal20,condition20).
hasCondition(goal21,condition21).
hasCondition(goal22,condition22).
hasCondition(goal23,condition23).
hasCondition(goal24,condition24).
hasCondition(goal25,condition25).
hasCondition(goal26,condition26).
hasCondition(goal27,condition27).
hasCondition(goal28,condition28).
hasCondition(goal29,condition29).
hasCondition(goal30,condition30).
hasCondition(goal31,condition31).
hasCondition(goal32,condition32).
hasCondition(goal33,condition33).
hasCondition(goal34,condition34).
hasCondition(goal35,condition35).
hasCondition(goal36,condition36).
hasCondition(goal37,condition37).
hasCondition(goal38,condition38).
hasCondition(goal39,condition39).
hasCondition(goal40,condition40).
hasCondition(goal41,condition41).
hasCondition(goal42,condition42).
hasCondition(goal43,condition43).
hasCondition(goal44,condition44).
hasCondition(goal45,condition45).
hasCondition(goal46,condition46).
hasCondition(goal47,condition47).
hasCondition(goal48,condition48).
hasCondition(goal49,condition49).
hasCondition(goal50,condition50).
hasCondition(goal51,condition51).


hasRelationArtefact(cone,corda,relation32).
hasRelationArtefact(cone,corda,relation35).
hasRelationArtefact(fita,corda,relation38).
hasRelationArtefact(fita,corda,relation54).
hasRelationArtefact(carretilha,bastao_universal,relation27).
hasRelationArtefact(carretilha,bastao_universal,relation30).
hasRelationArtefact(corda,bastao_universal,relation44).
hasRelationArtefact(corda,sela,relation36).
hasRelationArtefact(corda,sela,relation70).
hasRelationArtefact(corda,sela,relation73).
hasRelationArtefact(corda,colar,relation33).
hasRelationArtefact(corda,colar,relation69).
hasRelationArtefact(corda,bastao_garra,relation28).
hasRelationArtefact(corda,bastao_garra,relation31).
hasRelationArtefact(corda,bastao_garra,relation40).
hasRelationArtefact(bastao_universal,bastao_garra,relation41).
hasRelationArtefact(bastao_universal,bastao_garra,relation42).
hasRelationArtefact(bastao_universal,estopo,relation45).
hasRelationArtefact(bastao_universal,estopo,relation51).
hasRelationArtefact(bastao_universal,estopo,relation58).
hasRelationArtefact(bastao_universal,chave_catraca,relation29).
hasRelationArtefact(testador_de_corrente_de_fulga,chave_catraca,relation46).
hasRelationArtefact(testador_de_corrente_de_fulga,condutor,relation39).
hasRelationArtefact(testador_de_corrente_de_fulga,condutor,relation50).
hasRelationArtefact(testador_de_corrente_de_fulga,condutor,relation67).
hasRelationArtefact(sela,isolador_de_pedestal_velho,relation53).
hasRelationArtefact(sela,isolador_de_pedestal_velho,relation55).
hasRelationArtefact(sela,isolador_de_pedestal_velho,relation56).
hasRelationArtefact(sela,isolador_de_pedestal_novo,relation43).
hasRelationArtefact(sela,isolador_de_pedestal_novo,relation57).
hasRelationArtefact(sela,isolador_de_pedestal_novo,relation59).
hasRelationArtefact(colar,isolador_de_pedestal_novo,relation60).
hasRelationArtefact(colar,isolador_de_pedestal_novo,relation63).
hasRelationArtefact(colar,isolador_de_pedestal_novo,relation64).
hasRelationArtefact(colar,isolador_de_pedestal_novo,relation66).
hasRelationArtefact(bastao_garra,isolador_de_pedestal_novo,relation72).
hasRelationArtefact(bastao_garra,conector,relation49).
hasRelationArtefact(bastao_garra,conector,relation65).
hasRelationArtefact(estopo,conector,relation68).
hasRelationArtefact(estopo,chão,relation3).
hasRelationArtefact(estopo,torres-subestacao,relation4).
hasRelationArtefact(estopo,torres-subestacao,relation37).
hasRelationArtefact(chave_catraca,torres-subestacao,relation61).
hasRelationArtefact(chave_catraca,torres-subestacao,relation62).
hasRelationArtefact(chave_catraca,torres-subestacao,relation71).
hasRelationArtefact(chave_catraca,torres-subestacao,relation74).
hasRelationArtefact(chave_catraca,cavalete,relation5).
hasRelationArtefact(condutor,cavalete,relation6).
hasRelationArtefact(condutor,cavalete,relation7).
hasRelationArtefact(torre,cavalete,relation8).
hasRelationArtefact(isolador_de_pedestal_velho,cavalete,relation9).
hasRelationArtefact(isolador_de_pedestal_novo,cavalete,relation10).
hasRelationArtefact(isolador_de_pedestal_novo,cavalete,relation11).
hasRelationArtefact(conector,cavalete,relation12).
hasRelationArtefact(conector,cavalete,relation13).
hasRelationArtefact(conector,cavalete,relation14).
hasRelationArtefact(luva,cavalete,relation15).
hasRelationArtefact(óculos,cavalete,relation16).
hasRelationArtefact(chão,cavalete,relation17).
hasRelationArtefact(torres-subestacao,cavalete,relation18).
hasRelationArtefact(alcool_isopropilico,cavalete,relation19).
hasRelationArtefact(pano_seco,cavalete,relation20).
hasRelationArtefact(pano_seco,cavalete,relation21).
hasRelationArtefact(pano_seco,cavalete,relation22).
hasRelationArtefact(parafuso,cavalete,relation23).
hasRelationArtefact(parafuso,cavalete,relation24).
hasRelationArtefact(parafuso,pano_seco,relation26).
hasRelationArtefact(parafuso,parafuso,relation47).
hasRelationArtefact(parafuso,parafuso,relation48).
hasRelationArtefact(parafuso,parafuso,relation52).

hasConditionRel(sinalizacao,relation4).
hasConditionRel(posicionamento-cavalete,relation5).
hasConditionRel(posicionamento-cavalete,relation6).
hasConditionRel(posicionamento-cavalete,relation7).
hasConditionRel(posicionamento-cavalete,relation8).
hasConditionRel(posicionamento-cavalete,relation9).
hasConditionRel(posicionamento-cavalete,relation10).
hasConditionRel(posicionamento-cavalete,relation11).
hasConditionRel(posicionamento-cavalete,relation12).
hasConditionRel(posicionamento-cavalete,relation13).
hasConditionRel(posicionamento-cavalete,relation14).
hasConditionRel(posicionamento-cavalete,relation15).
hasConditionRel(posicionamento-cavalete,relation16).
hasConditionRel(posicionamento-cavalete,relation17).
hasConditionRel(posicionamento-cavalete,relation18).
hasConditionRel(posicionamento-cavalete,relation19).
hasConditionRel(posicionamento-cavalete,relation20).
hasConditionRel(posicionamento-cavalete,relation21).
hasConditionRel(posicionamento-cavalete,relation22).
hasConditionRel(posicionamento-cavalete,relation23).
hasConditionRel(posicionamento-cavalete,relation24).
hasConditionRel(limpar-ferramenta,relation26).
hasConditionRel(limpar-ferramenta,relation27).
hasConditionRel(limpar-ferramenta,relation28).
hasConditionRel(limpar-ferramenta,relation29).
hasConditionRel(medicao-corrente-fulga-inicio-manutencao,relation27).
hasConditionRel(medicao-corrente-fulga-inicio-manutencao,relation28).
hasConditionRel(medicao-corrente-fulga-durante-manutencao,relation27).
hasConditionRel(medicao-corrente-fulga-durante-manutencao,relation28).
hasConditionRel(medicao-corrente-fulga-final-operacao,relation27).
hasConditionRel(medicao-corrente-fulga-final-operacao,relation28).
hasConditionRel(teste-impedancia-corda,relation32).
hasConditionRel(interpolar-corda-bastao-universal,relation33).
hasConditionRel(fixar-carretilha-corda-bastao-universal,relation35).
hasConditionRel(instalar-sela-corda-lado-1,relation36).
hasConditionRel(instalar-sela-corda-lado-1,relation37).
hasConditionRel(fixar-bastao-garra-colar-sela,relation38).
hasConditionRel(fixar-bastao-garra-lado-1-condutor,relation39).
hasConditionRel(instalar-sela-colar-coluna-lado-2,relation38).
hasConditionRel(fixar-bastao-garra-invertido-lado-2,relation39).
hasConditionRel(fixar-carretilha-corda-fibra-sintetica-ponta-bastao,relation40).
hasConditionRel(girar-sela-erguer-bastao,relation42).
hasConditionRel(enforcar-estopo-alto-isolador,relation43).
hasConditionRel(conectar-corda-estopo,relation44).
hasConditionRel(conectar-corda-estopo,relation45).
hasConditionRel(bastao-universal-chave-catraca-saltar-parafusos,relation46).
hasConditionRel(bastao-universal-chave-catraca-saltar-parafusos,relation47).
hasConditionRel(retirar-parafuso-cima,relation48).
hasConditionRel(retirar-parafuso-cima,relation49).
hasConditionRel(retirar-parafuso-cima,relation50).
hasConditionRel(tencionar-corda-estopo,relation51).
hasConditionRel(tirar-parafusos-baixo-isolador-chave-catraca,relation52).
hasConditionRel(tirar-parafusos-baixo-isolador-chave-catraca,relation53).
hasConditionRel(passar-corda-base-isolador-chave-catraca,relation54).
hasConditionRel(passar-corda-base-isolador-chave-catraca,relation55).
hasConditionRel(corda-erguer-isolador,relation56).
hasConditionRel(estopo-isolador,relation57).
hasConditionRel(estopo-isolador,relation58).
hasConditionRel(suspender-isolador,relation59).
hasConditionRel(engate-corda-guia,relation60).
hasConditionRel(parafusar-isolador-coluna-chave-catraca,relation61).
hasConditionRel(parafusar-isolador-coluna-chave-catraca,relation62).
hasConditionRel(parafusar-isolador-coluna-chave-catraca,relation63).
hasConditionRel(fechar-conector-bastao-universal,relation64).
hasConditionRel(fechar-conector-bastao-universal,relation65).
hasConditionRel(fechar-conector-bastao-universal,relation66).
hasConditionRel(desconectar-batao-garra-conector,relation67).
hasConditionRel(desconectar-batao-garra-conector,relation68).
hasConditionRel(retirar-bastao-garra,relation69).
hasConditionRel(retirar-sela-colar-bastao-garra-lado-1,relation70).
hasConditionRel(retirar-sela-colar-bastao-garra-lado-1,relation71).
hasConditionRel(retirar-estopo-isolador,relation72).
hasConditionRel(retirar-sela-colar-bastao-garra-lado-2,relation73).
hasConditionRel(retirar-sela-colar-bastao-garra-lado-2,relation74).



allocation(agente01,supervisor).
allocation(agente02,observador).
allocation(agente03,executor01).
allocation(agente04,executor02).
allocation(agente05,executor03).
allocation(agente06,executor04).
allocation(agente07,executor05).
allocation(agente08,executor06).
allocation(agente09,executor07).

existGroupSafaty(ruido,group_green).
existGroupSafaty(vibracao,group_green).
existGroupSafaty(radiacao_ionizante,group_green).
existGroupSafaty(radiacao_nao_ionizante,group_green).
existGroupSafaty(frio,group_green).
existGroupSafaty(calor,group_green).
existGroupSafaty(pressao_anormal,group_green).
existGroupSafaty(umidade,group_green).
existGroupSafaty(poeira,group_red).
existGroupSafaty(fumo,group_red).
existGroupSafaty(neblina,group_red).
existGroupSafaty(gas,group_red).
existGroupSafaty(vapor,group_red).
existGroupSafaty(substancia_composta_ou_produtos_quimicos_gerais,group_red).
existGroupSafaty(risco_ergonimico,group_yellow).
existGroupSafaty(esforco_fisico_intenso,group_yellow).
existGroupSafaty(levantamento_transporte_manual_peso,group_yellow).
existGroupSafaty(controle_rigido_produtividade,group_yellow).
existGroupSafaty(imposicao_ritmo_excessivo,group_yellow).
existGroupSafaty(trabalho_em_turno_e_noturno,group_yellow).
existGroupSafaty(jornada_de_trabalho_prolongadas,group_yellow).
existGroupSafaty(monotonia_e_repetitividade,group_yellow).
existGroupSafaty(outras_situacoes_causadoras_estresse_fisico_psiquico,group_yellow).
existGroupSafaty(virus,group_brown).
existGroupSafaty(bacteria,group_brown).
existGroupSafaty(fungos,group_brown).
existGroupSafaty(parasitas,group_brown).
existGroupSafaty(bacilos,group_brown).
existGroupSafaty(riscos_de_acidentes,group_blue).
existGroupSafaty(arranjo_fisico_inadequado,group_blue).
existGroupSafaty(maquinas_equipamentos_sem_protecao,group_blue).
existGroupSafaty(iluminacao_inadequada,group_blue).
existGroupSafaty(eletricidade,group_blue).
existGroupSafaty(probabilidade_incendio_explosao,group_blue).
existGroupSafaty(armazenamento_inadequado,group_blue).
existGroupSafaty(animais_peconhentos,group_blue).
existGroupSafaty(outras_situacoes_de_risco_que_poderao_gerar_acidentes_fatais,group_blue).


hasMission(goal1,missao00).
hasMission(goal2,missao00).
hasMission(goal3,missao01-01).
hasMission(goal4,missao01-02).
hasMission(goal5,missao01-03).
hasMission(goal6,missao01-04).
hasMission(goal7,missao01-05).
hasMission(goal8,missao01-06).
hasMission(goal9,missao02).
hasMission(goal10,missao03).
hasMission(goal11,missao03).
hasMission(goal12,missao03).
hasMission(goal13,missao03).
hasMission(goal14,missao03).
hasMission(goal15,missao03).
hasMission(goal16,missao03).
hasMission(goal17,missao03).
hasMission(goal18,missao03).
hasMission(goal19,missao03).
hasMission(goal20,missao04).
hasMission(goal21,missao04).
hasMission(goal22,missao04).
hasMission(goal23,missao04).
hasMission(goal24,missao04).
hasMission(goal25,missao05).
hasMission(goal26,missao05).
hasMission(goal27,missao05).
hasMission(goal28,missao05).
hasMission(goal29,missao06).
hasMission(goal30,missao06).
hasMission(goal31,missao07).
hasMission(goal32,missao07).
hasMission(goal33,missao07).
hasMission(goal34,missao08).
hasMission(goal35,missao08).
hasMission(goal36,missao08).
hasMission(goal37,missao09).
hasMission(goal38,missao09).
hasMission(goal39,missao09).
hasMission(goal40,missao10).
hasMission(goal41,missao11).
hasMission(goal42,missao11).
hasMission(goal43,missao11).
hasMission(goal44,missao11).



hasPlanSuper(goal1,plan1).
hasPlanSuper(goal2,plan1).
hasPlanSuper(goal3,plan7).
hasPlanSuper(goal4,plan7).
hasPlanSuper(goal5,plan7).
hasPlanSuper(goal6,plan7).
hasPlanSuper(goal7,plan8).
hasPlanSuper(goal8,plan5).
hasPlanSuper(goal9,plan1).
hasPlanSuper(goal10,plan3).
hasPlanSuper(goal12,plan3).
hasPlanSuper(goal13,plan3).
hasPlanSuper(goal14,plan3).
hasPlanSuper(goal15,plan3).
hasPlanSuper(goal16,plan3).
hasPlanSuper(goal17,plan3).
hasPlanSuper(goal18,plan3).
hasPlanSuper(goal19,plan3).
hasPlanSuper(goal20,plan3).
hasPlanSuper(goal21,plan3).
hasPlanSuper(goal22,plan3).
hasPlanSuper(goal23,plan3).
hasPlanSuper(goal84,plan3).
hasPlanSuper(goal25,plan2).
hasPlanSuper(goal25,plan1).
hasPlanSuper(goal26,plan4).
hasPlanSuper(goal27,plan4).
hasPlanSuper(goal29,plan5).
hasPlanSuper(goal30,plan5).
hasPlanSuper(goal31,plan5).
hasPlanSuper(goal32,plan5).
hasPlanSuper(goal33,plan5).
hasPlanSuper(goal34,plan5).
hasPlanSuper(goal35,plan5).
hasPlanSuper(goal36,plan5).
hasPlanSuper(goal37,plan5).
hasPlanSuper(goal38,plan5).
hasPlanSuper(goal39,plan5).
hasPlanSuper(goal40,plan5).
hasPlanSuper(goal41,plan5).
hasPlanSuper(goal42,plan5).
hasPlanSuper(goal43,plan5).
hasPlanSuper(goal44,plan5).
hasPlanSuper(goal45,plan5).
hasPlanSuper(goal46,plan2).
hasPlanSuper(goal47,plan6).
hasPlanSuper(goal48,plan6).
hasPlanSuper(goal50,plan8).
hasPlanSuper(goal51,plan6).

obligation(supervisor,missao10).
obligation(observador,missao11).
obligation(executor01,missao01-01).
obligation(executor01,missao02).
obligation(executor01,missao03).
obligation(executor01,missao07).
obligation(executor01,missao08).
obligation(executor01,missao09).
obligation(executor01,missao10).
obligation(executor01,missao11).
obligation(executor02,missao00).
obligation(executor02,missao01-01).
obligation(executor02,missao01-06).
obligation(executor02,missao02).
obligation(executor02,missao03).
obligation(executor02,missao07).
obligation(executor02,missao08).
obligation(executor02,missao09).
obligation(executor02,missao11).
obligation(executor03,missao00).
obligation(executor03,missao01-01).
obligation(executor03,missao01-06).
obligation(executor03,missao02).
obligation(executor03,missao03).
obligation(executor03,missao04).
obligation(executor03,missao05).
obligation(executor03,missao08).
obligation(executor03,missao09).
obligation(executor03,missao11).
obligation(executor04,missao00).
obligation(executor04,missao01-02).
obligation(executor04,missao02).
obligation(executor04,missao03).
obligation(executor04,missao04).
obligation(executor04,missao05).
obligation(executor04,missao08).
obligation(executor04,missao09).
obligation(executor04,missao11).
obligation(executor05,missao00).
obligation(executor05,missao01-03).
obligation(executor05,missao02).
obligation(executor05,missao04).
obligation(executor05,missao05).
obligation(executor05,missao08).
obligation(executor05,missao09).
obligation(executor05,missao11).
obligation(executor06,missao00).
obligation(executor06,missao01-04).
obligation(executor06,missao02).
obligation(executor06,missao06).
obligation(executor06,missao07).
obligation(executor06,missao08).
obligation(executor06,missao09).
obligation(executor06,missao11).
obligation(executor07,missao00).
obligation(executor07,missao01-05).
obligation(executor07,missao02).
obligation(executor07,missao06).
obligation(executor07,missao07).
obligation(executor07,missao08).
obligation(executor07,missao09).
obligation(executor07,missao11).


isInstanceOf(riskFixarBastaoGarraColarSela,risk).
isInstanceOf(riskBataoGarraLado1Condutor,risk).
isInstanceOf(risKInstalarSelaColarColunaLado2,risk).
isInstanceOf(risKInstalarSelaColarColunaLado2,risk).
isInstanceOf(risKInstalarSelaColarColunaLado2,risk).
isInstanceOf(risKInstalarSelaColarColunaLado2,risk).
isInstanceOf(riskGirarSelaErguerBastao,risk).
isInstanceOf(riskEnforcarEstopoAltoIsolador01,risk).
isInstanceOf(riskEnforcarEstopoAltoIsolador02,risk).


hasNewGoalProbability(goal7,longConsequence16,75).
hasNewGoalProbability(goal8,longConsequence16,75).
hasNewGoalProbability(goal9,longConsequence16,75).
hasNewGoalProbability(goal10,longConsequence16,75).
hasNewGoalProbability(goal11,longConsequence16,75).
hasNewGoalProbability(goal12,longConsequence16,75).
hasNewGoalProbability(goal13,longConsequence16,75).
hasNewGoalProbability(goal14,longConsequence16,75).
hasNewGoalProbability(goal15,longConsequence16,75).
hasNewGoalProbability(goal16,longConsequence16,75).
hasNewGoalProbability(goal17,longConsequence16,75).
hasNewGoalProbability(goal18,longConsequence16,75).
hasNewGoalProbability(goal19,longConsequence16,75).
hasNewGoalProbability(goal20,longConsequence16,75).
hasNewGoalProbability(goal21,longConsequence16,75).
hasNewGoalProbability(goal22,longConsequence16,75).
hasNewGoalProbability(goal23,longConsequence16,75).
hasNewGoalProbability(goal24,longConsequence16,75).
hasNewGoalProbability(goal25,longConsequence16,75).
hasNewGoalProbability(goal26,longConsequence16,75).
hasNewGoalProbability(goal27,longConsequence16,75).
hasNewGoalProbability(goal28,longConsequence16,75).
hasNewGoalProbability(goal29,longConsequence16,75).
hasNewGoalProbability(goal30,longConsequence16,75).
hasNewGoalProbability(goal31,longConsequence16,75).
hasNewGoalProbability(goal32,longConsequence16,75).
hasNewGoalProbability(goal33,longConsequence16,75).
hasNewGoalProbability(goal34,longConsequence16,75).
hasNewGoalProbability(goal35,longConsequence16,75).
hasNewGoalProbability(goal36,longConsequence16,75).
hasNewGoalProbability(goal37,longConsequence16,75).
hasNewGoalProbability(goal38,longConsequence16,75).
hasNewGoalProbability(goal39,longConsequence16,75).
hasNewGoalProbability(goal40,longConsequence16,75).
hasNewGoalProbability(goal41,longConsequence16,75).
hasNewGoalProbability(goal42,longConsequence16,75).
hasNewGoalProbability(goal43,longConsequence16,75).
hasNewGoalProbability(goal44,longConsequence16,75).
hasNewGoalProbability(goal45,longConsequence16,75).
hasNewGoalProbability(goal46,longConsequence16,75).
hasNewGoalProbability(goal47,longConsequence16,75).
hasNewGoalProbability(goal48,longConsequence16,75).
hasNewGoalProbability(goal49,longConsequence16,75).
hasNewGoalProbability(goal50,longConsequence16,75).
hasNewGoalProbability(goal51,longConsequence16,75).
hasNewGoalProbability(goal52,longConsequence16,75).
hasNewGoalProbability(goal54,longConsequence16,75).
hasNewGoalProbability(goal55,longConsequence16,75).
hasNewGoalProbability(goal56,longConsequence16,75).
hasNewGoalProbability(goal57,longConsequence16,75).
hasNewGoalProbability(goal7,longConsequence17,75).
hasNewGoalProbability(goal8,longConsequence18,75).
hasNewGoalProbability(goal9,longConsequence19,75).
hasNewGoalProbability(goal10,longConsequence20,75).
hasNewGoalProbability(goal11,longConsequence21,75).
hasNewGoalProbability(goal12,longConsequence22,75).
hasNewGoalProbability(goal13,longConsequence23,75).
hasNewGoalProbability(goal14,longConsequence24,75).
hasNewGoalProbability(goal15,longConsequence25,75).
hasNewGoalProbability(goal16,longConsequence26,75).
hasNewGoalProbability(goal17,longConsequence27,75).
hasNewGoalProbability(goal18,longConsequence28,75).
hasNewGoalProbability(goal19,longConsequence29,75).
hasNewGoalProbability(goal20,longConsequence30,75).
hasNewGoalProbability(goal21,longConsequence31,75).
hasNewGoalProbability(goal22,longConsequence32,75).
hasNewGoalProbability(goal23,longConsequence33,75).
hasNewGoalProbability(goal24,longConsequence34,75).
hasNewGoalProbability(goal25,longConsequence35,75).
hasNewGoalProbability(goal26,longConsequence36,75).
hasNewGoalProbability(goal27,longConsequence37,75).
hasNewGoalProbability(goal28,longConsequence38,75).
hasNewGoalProbability(goal29,longConsequence39,75).
hasNewGoalProbability(goal30,longConsequence40,75).
hasNewGoalProbability(goal31,longConsequence41,75).
hasNewGoalProbability(goal32,longConsequence42,75).
hasNewGoalProbability(goal33,longConsequence43,75).
hasNewGoalProbability(goal34,longConsequence44,75).
hasNewGoalProbability(goal35,longConsequence45,75).
hasNewGoalProbability(goal36,longConsequence46,75).
hasNewGoalProbability(goal37,longConsequence47,75).
hasNewGoalProbability(goal38,longConsequence48,75).
hasNewGoalProbability(goal39,longConsequence49,75).
hasNewGoalProbability(goal40,longConsequence50,75).
hasNewGoalProbability(goal41,longConsequence51,75).
hasNewGoalProbability(goal42,longConsequence52,75).
hasNewGoalProbability(goal43,longConsequence53,75).
hasNewGoalProbability(goal44,longConsequence54,75).
hasNewGoalProbability(goal45,longConsequence55,75).
hasNewGoalProbability(goal46,longConsequence56,75).
hasNewGoalProbability(goal47,longConsequence57,75).
hasNewGoalProbability(goal48,longConsequence58,75).
hasNewGoalProbability(goal49,longConsequence59,75).
hasNewGoalProbability(goal50,longConsequence60,75).
hasNewGoalProbability(goal51,longConsequence61,75).
hasNewGoalProbability(goal52,longConsequence62,75).
hasNewGoalProbability(goal54,longConsequence63,75).
hasNewGoalProbability(goal55,longConsequence64,75).
hasNewGoalProbability(goal56,longConsequence65,75).
hasNewGoalProbability(goal57,longConsequence66,75).
hasNewGoalProbability(goal7,longConsequence67,75).
hasNewGoalProbability(goal8,longConsequence68,75).
hasNewGoalProbability(goal9,longConsequence69,75).
hasNewGoalProbability(goal10,longConsequence70,75).
hasNewGoalProbability(goal11,longConsequence71,75).
hasNewGoalProbability(goal12,longConsequence72,75).
hasNewGoalProbability(goal13,longConsequence73,75).
hasNewGoalProbability(goal14,longConsequence74,75).
hasNewGoalProbability(goal15,longConsequence75,75).
hasNewGoalProbability(goal16,longConsequence76,75).
hasNewGoalProbability(goal17,longConsequence77,75).
hasNewGoalProbability(goal18,longConsequence78,75).
hasNewGoalProbability(goal19,longConsequence79,75).
hasNewGoalProbability(goal20,longConsequence80,75).
hasNewGoalProbability(goal21,longConsequence81,75).
hasNewGoalProbability(goal22,longConsequence82,75).
hasNewGoalProbability(goal23,longConsequence83,75).
hasNewGoalProbability(goal24,longConsequence84,75).
hasNewGoalProbability(goal25,longConsequence85,75).
hasNewGoalProbability(goal26,longConsequence86,75).
hasNewGoalProbability(goal27,longConsequence87,75).
hasNewGoalProbability(goal28,longConsequence88,75).
hasNewGoalProbability(goal29,longConsequence89,75).
hasNewGoalProbability(goal30,longConsequence90,75).
hasNewGoalProbability(goal31,longConsequence91,75).
hasNewGoalProbability(goal32,longConsequence92,75).
hasNewGoalProbability(goal33,longConsequence93,75).
hasNewGoalProbability(goal34,longConsequence94,75).
hasNewGoalProbability(goal35,longConsequence95,75).
hasNewGoalProbability(goal36,longConsequence96,75).
hasNewGoalProbability(goal37,longConsequence97,75).
hasNewGoalProbability(goal38,longConsequence98,75).
hasNewGoalProbability(goal39,longConsequence99,75).
hasNewGoalProbability(goal40,longConsequence100,75).
hasNewGoalProbability(goal41,longConsequence101,75).
hasNewGoalProbability(goal42,longConsequence102,75).
hasNewGoalProbability(goal43,longConsequence103,75).
hasNewGoalProbability(goal44,longConsequence104,75).
hasNewGoalProbability(goal45,longConsequence105,75).
hasNewGoalProbability(goal46,longConsequence106,75).
hasNewGoalProbability(goal47,longConsequence107,75).
hasNewGoalProbability(goal48,longConsequence108,75).
hasNewGoalProbability(goal49,longConsequence109,75).
hasNewGoalProbability(goal50,longConsequence110,75).
hasNewGoalProbability(goal51,longConsequence111,75).
hasNewGoalProbability(goal52,longConsequence112,75).
hasNewGoalProbability(goal53,longConsequence113,75).
hasNewGoalProbability(goal55,longConsequence114,75).
hasNewGoalProbability(goal56,longConsequence115,75).
hasNewGoalProbability(goal57,longConsequence116,75).
hasNewGoalProbability(goal8,longConsequence117,75).
hasNewGoalProbability(goal8,longConsequence118,75).
hasNewGoalProbability(goal9,longConsequence119,75).
hasNewGoalProbability(goal10,longConsequence120,75).
hasNewGoalProbability(goal11,longConsequence121,75).
hasNewGoalProbability(goal12,longConsequence122,75).
hasNewGoalProbability(goal13,longConsequence123,75).
hasNewGoalProbability(goal14,longConsequence124,75).
hasNewGoalProbability(goal15,longConsequence125,75).
hasNewGoalProbability(goal16,longConsequence126,75).
hasNewGoalProbability(goal17,longConsequence127,75).
hasNewGoalProbability(goal18,longConsequence128,75).
hasNewGoalProbability(goal19,longConsequence129,75).
hasNewGoalProbability(goal20,longConsequence130,75).
hasNewGoalProbability(goal21,longConsequence131,75).
hasNewGoalProbability(goal22,longConsequence132,75).
hasNewGoalProbability(goal23,longConsequence133,75).
hasNewGoalProbability(goal24,longConsequence134,75).
hasNewGoalProbability(goal25,longConsequence135,75).
hasNewGoalProbability(goal26,longConsequence136,75).
hasNewGoalProbability(goal27,longConsequence137,75).
hasNewGoalProbability(goal28,longConsequence138,75).
hasNewGoalProbability(goal29,longConsequence139,75).
hasNewGoalProbability(goal30,longConsequence140,75).
hasNewGoalProbability(goal31,longConsequence141,75).
hasNewGoalProbability(goal32,longConsequence142,75).
hasNewGoalProbability(goal33,longConsequence143,75).
hasNewGoalProbability(goal34,longConsequence144,75).
hasNewGoalProbability(goal35,longConsequence145,75).
hasNewGoalProbability(goal36,longConsequence146,75).
hasNewGoalProbability(goal37,longConsequence147,75).
hasNewGoalProbability(goal38,longConsequence148,75).
hasNewGoalProbability(goal39,longConsequence149,75).
hasNewGoalProbability(goal40,longConsequence150,75).
hasNewGoalProbability(goal41,longConsequence151,75).
hasNewGoalProbability(goal42,longConsequence152,75).
hasNewGoalProbability(goal43,longConsequence153,75).
hasNewGoalProbability(goal44,longConsequence154,75).
hasNewGoalProbability(goal45,longConsequence155,75).
hasNewGoalProbability(goal46,longConsequence156,75).
hasNewGoalProbability(goal47,longConsequence157,75).
hasNewGoalProbability(goal48,longConsequence158,75).
hasNewGoalProbability(goal49,longConsequence159,75).
hasNewGoalProbability(goal50,longConsequence160,75).
hasNewGoalProbability(goal51,longConsequence161,75).
hasNewGoalProbability(goal52,longConsequence162,75).
hasNewGoalProbability(goal53,longConsequence163,75).
hasNewGoalProbability(goal54,longConsequence164,75).
hasNewGoalProbability(goal55,longConsequence165,75).
hasNewGoalProbability(goal56,longConsequence166,75).
hasNewGoalProbability(goal57,longConsequence167,75).
hasNewGoalProbability(goal7,longConsequence168,75).
hasNewGoalProbability(goal9,longConsequence169,75).
hasNewGoalProbability(goal10,longConsequence170,75).
hasNewGoalProbability(goal11,longConsequence171,75).
hasNewGoalProbability(goal12,longConsequence172,75).
hasNewGoalProbability(goal13,longConsequence173,75).
hasNewGoalProbability(goal14,longConsequence174,75).
hasNewGoalProbability(goal15,longConsequence175,75).
hasNewGoalProbability(goal16,longConsequence176,75).
hasNewGoalProbability(goal17,longConsequence177,75).
hasNewGoalProbability(goal18,longConsequence178,75).
hasNewGoalProbability(goal19,longConsequence179,75).
hasNewGoalProbability(goal20,longConsequence180,75).
hasNewGoalProbability(goal21,longConsequence181,75).
hasNewGoalProbability(goal22,longConsequence182,75).
hasNewGoalProbability(goal23,longConsequence183,75).
hasNewGoalProbability(goal24,longConsequence184,75).
hasNewGoalProbability(goal25,longConsequence185,75).
hasNewGoalProbability(goal26,longConsequence186,75).
hasNewGoalProbability(goal27,longConsequence187,75).
hasNewGoalProbability(goal28,longConsequence188,75).
hasNewGoalProbability(goal29,longConsequence189,75).
hasNewGoalProbability(goal30,longConsequence190,75).
hasNewGoalProbability(goal31,longConsequence191,75).
hasNewGoalProbability(goal32,longConsequence192,75).
hasNewGoalProbability(goal33,longConsequence193,75).
hasNewGoalProbability(goal34,longConsequence194,75).
hasNewGoalProbability(goal35,longConsequence195,75).
hasNewGoalProbability(goal36,longConsequence196,75).
hasNewGoalProbability(goal37,longConsequence197,75).
hasNewGoalProbability(goal38,longConsequence198,75).
hasNewGoalProbability(goal39,longConsequence199,75).
hasNewGoalProbability(goal40,longConsequence200,75).
hasNewGoalProbability(goal41,longConsequence201,75).
hasNewGoalProbability(goal42,longConsequence202,75).
hasNewGoalProbability(goal43,longConsequence203,75).
hasNewGoalProbability(goal44,longConsequence204,75).
hasNewGoalProbability(goal45,longConsequence205,75).
hasNewGoalProbability(goal46,longConsequence206,75).
hasNewGoalProbability(goal47,longConsequence207,75).
hasNewGoalProbability(goal48,longConsequence208,75).
hasNewGoalProbability(goal49,longConsequence209,75).
hasNewGoalProbability(goal50,longConsequence210,75).
hasNewGoalProbability(goal51,longConsequence211,75).
hasNewGoalProbability(goal52,longConsequence212,75).
hasNewGoalProbability(goal53,longConsequence213,75).
hasNewGoalProbability(goal54,longConsequence214,75).
hasNewGoalProbability(goal55,longConsequence215,75).
hasNewGoalProbability(goal56,longConsequence216,75).
hasNewGoalProbability(goal57,longConsequence217,75).
hasNewGoalProbability(goal10,longConsequence218,85).
hasNewGoalProbability(goal11,longConsequence219,85).
hasNewGoalProbability(goal12,longConsequence220,85).
hasNewGoalProbability(goal13,longConsequence221,85).
hasNewGoalProbability(goal14,longConsequence222,85).
hasNewGoalProbability(goal15,longConsequence223,85).
hasNewGoalProbability(goal16,longConsequence224,85).
hasNewGoalProbability(goal17,longConsequence225,85).
hasNewGoalProbability(goal18,longConsequence226,85).
hasNewGoalProbability(goal19,longConsequence227,85).
hasNewGoalProbability(goal20,longConsequence228,85).
hasNewGoalProbability(goal21,longConsequence229,85).
hasNewGoalProbability(goal22,longConsequence230,85).
hasNewGoalProbability(goal23,longConsequence231,85).
hasNewGoalProbability(goal24,longConsequence232,85).
hasNewGoalProbability(goal25,longConsequence233,85).
hasNewGoalProbability(goal26,longConsequence234,85).
hasNewGoalProbability(goal27,longConsequence235,85).
hasNewGoalProbability(goal28,longConsequence236,85).
hasNewGoalProbability(goal29,longConsequence237,85).
hasNewGoalProbability(goal30,longConsequence238,85).
hasNewGoalProbability(goal31,longConsequence239,85).
hasNewGoalProbability(goal32,longConsequence240,85).
hasNewGoalProbability(goal33,longConsequence241,85).
hasNewGoalProbability(goal34,longConsequence242,85).
hasNewGoalProbability(goal35,longConsequence243,85).
hasNewGoalProbability(goal36,longConsequence244,85).
hasNewGoalProbability(goal37,longConsequence245,85).
hasNewGoalProbability(goal38,longConsequence246,85).
hasNewGoalProbability(goal39,longConsequence247,85).
hasNewGoalProbability(goal40,longConsequence248,85).
hasNewGoalProbability(goal41,longConsequence249,85).
hasNewGoalProbability(goal42,longConsequence250,85).
hasNewGoalProbability(goal43,longConsequence251,85).
hasNewGoalProbability(goal44,longConsequence252,85).
hasNewGoalProbability(goal45,longConsequence253,85).
hasNewGoalProbability(goal46,longConsequence254,85).
hasNewGoalProbability(goal47,longConsequence255,85).
hasNewGoalProbability(goal48,longConsequence256,85).
hasNewGoalProbability(goal49,longConsequence257,85).
hasNewGoalProbability(goal50,longConsequence258,85).
hasNewGoalProbability(goal51,longConsequence259,85).
hasNewGoalProbability(goal52,longConsequence260,85).
hasNewGoalProbability(goal53,longConsequence261,85).
hasNewGoalProbability(goal54,longConsequence262,85).
hasNewGoalProbability(goal55,longConsequence263,85).
hasNewGoalProbability(goal56,longConsequence264,85).
hasNewGoalProbability(goal57,longConsequence265,85).
hasNewGoalProbability(goal24,longConsequence266,50).
hasNewGoalProbability(goal44,longConsequence266,50).
hasNewGoalProbability(goal46,longConsequence266,50).
hasNewGoalProbability(goal32,longConsequence266,50).
hasNewGoalProbability(goal33,longConsequence266,50).
hasNewGoalProbability(goal24,longConsequence267,50).
hasNewGoalProbability(goal44,longConsequence267,50).
hasNewGoalProbability(goal46,longConsequence267,50).
hasNewGoalProbability(goal32,longConsequence267,50).
hasNewGoalProbability(goal33,longConsequence267,50).
hasNewGoalProbability(goal24,longConsequence268,50).
hasNewGoalProbability(goal44,longConsequence268,50).
hasNewGoalProbability(goal46,longConsequence268,50).
hasNewGoalProbability(goal32,longConsequence268,50).
hasNewGoalProbability(goal33,longConsequence268,50).
hasNewGoalProbability(goal24,longConsequence269,50).
hasNewGoalProbability(goal44,longConsequence269,50).
hasNewGoalProbability(goal46,longConsequence269,50).
hasNewGoalProbability(goal32,longConsequence269,50).
hasNewGoalProbability(goal33,longConsequence269,50).
hasNewGoalProbability(goal24,longConsequence270,50).
hasNewGoalProbability(goal44,longConsequence270,50).
hasNewGoalProbability(goal46,longConsequence270,50).
hasNewGoalProbability(goal32,longConsequence270,50).
hasNewGoalProbability(goal33,longConsequence270,50).
hasNewGoalProbability(goal28,longConsequence271,50).
hasNewGoalProbability(goal35,longConsequence271,50).
hasNewGoalProbability(goal37,longConsequence271,50).
hasNewGoalProbability(goal43,longConsequence271,50).
hasNewGoalProbability(goal33,longConsequence271,50).
hasNewGoalProbability(goal49,longConsequence271,50).
hasNewGoalProbability(goal50,longConsequence271,50).
hasNewGoalProbability(goal28,longConsequence272,50).
hasNewGoalProbability(goal35,longConsequence272,50).
hasNewGoalProbability(goal37,longConsequence272,50).
hasNewGoalProbability(goal43,longConsequence272,50).
hasNewGoalProbability(goal33,longConsequence272,50).
hasNewGoalProbability(goal49,longConsequence272,50).
hasNewGoalProbability(goal50,longConsequence272,50).
hasNewGoalProbability(goal28,longConsequence273,50).
hasNewGoalProbability(goal35,longConsequence273,50).
hasNewGoalProbability(goal37,longConsequence273,50).
hasNewGoalProbability(goal43,longConsequence273,50).
hasNewGoalProbability(goal33,longConsequence273,50).
hasNewGoalProbability(goal49,longConsequence273,50).
hasNewGoalProbability(goal50,longConsequence273,50).
hasNewGoalProbability(goal28,longConsequence274,50).
hasNewGoalProbability(goal35,longConsequence274,50).
hasNewGoalProbability(goal37,longConsequence274,50).
hasNewGoalProbability(goal43,longConsequence274,50).
hasNewGoalProbability(goal33,longConsequence274,50).
hasNewGoalProbability(goal49,longConsequence274,50).
hasNewGoalProbability(goal50,longConsequence274,50).
hasNewGoalProbability(goal28,longConsequence275,50).
hasNewGoalProbability(goal35,longConsequence275,50).
hasNewGoalProbability(goal37,longConsequence275,50).
hasNewGoalProbability(goal43,longConsequence275,50).
hasNewGoalProbability(goal33,longConsequence275,50).
hasNewGoalProbability(goal49,longConsequence275,50).
hasNewGoalProbability(goal50,longConsequence275,50).
hasNewGoalProbability(goal23,longConsequence276,0).
hasNewGoalProbability(goal24,longConsequence276,0).
hasNewGoalProbability(goal32,longConsequence277,0).
hasNewGoalProbability(goal47,longConsequence277,0).
hasNewGoalProbability(goal48,longConsequence277,0).
hasNewGoalProbability(goal26,longConsequence278,0).
hasNewGoalProbability(goal27,longConsequence278,0).
hasNewGoalProbability(goal28,longConsequence278,0).
hasNewGoalProbability(goal39,longConsequence278,0).
hasNewGoalProbability(goal43,longConsequence278,0).
hasNewGoalProbability(goal27,longConsequence279,50).
hasNewGoalProbability(goal28,longConsequence279,50).
hasNewGoalProbability(goal35,longConsequence279,50).
hasNewGoalProbability(goal39,longConsequence279,50).
hasNewGoalProbability(goal27,longConsequence280,50).
hasNewGoalProbability(goal28,longConsequence280,50).
hasNewGoalProbability(goal35,longConsequence280,50).
hasNewGoalProbability(goal39,longConsequence280,50).
hasNewGoalProbability(goal28,longConsequence281,50).
hasNewGoalProbability(goal35,longConsequence281,50).
hasNewGoalProbability(goal39,longConsequence281,50).
hasNewGoalProbability(goal35,longConsequence282,50).
hasNewGoalProbability(goal39,longConsequence282,50).
hasNewGoalProbability(goal30,longConsequence283,50).
hasNewGoalProbability(goal35,longConsequence283,0).
hasNewGoalProbability(goal36,longConsequence283,0).
hasNewGoalProbability(goal37,longConsequence283,0).
hasNewGoalProbability(goal38,longConsequence283,0).
hasNewGoalProbability(goal39,longConsequence283,0).
hasNewGoalProbability(goal41,longConsequence283,0).
hasNewGoalProbability(goal43,longConsequence283,0).
hasNewGoalProbability(goal44,longConsequence283,0).




